### ISSUE TITLE
[Android only] App crashes on PlattformException

### ISSUE THREAD

**Issue by h4j4x** [ScerIO/packages.flutter#288]
**Describe the bug**
On Android I'm getting this error:
```
E/flutter ( 6854): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(PdfRendererException, io.scer.pdfx.PdfRendererException: Unknown error, Cause: null, Stacktrace: io.scer.pdfx.PdfRendererException: Unknown error
E/flutter ( 6854): 	at io.scer.pdfx.Messages.getPage(Messages.kt:147)
E/flutter ( 6854): 	at dev.flutter.pigeon.Pigeon$PdfxApi$-CC.lambda$setup$4(Pigeon.java:1223)
E/flutter ( 6854): 	at dev.flutter.pigeon.-$$Lambda$Pigeon$PdfxApi$Aa0CTw_-R6CZyCn-fCfwYs-3Fw8.onMessage(Unknown Source:2)
E/flutter ( 6854): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/flutter ( 6854): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/flutter ( 6854): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/flutter ( 6854): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/flutter ( 6854): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 6854): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 6854): 	at android.os.Looper.loop(Looper.java:236)
E/flutter ( 6854): 	at android.app.ActivityThread.main(ActivityThread.java:8061)
E/flutter ( 6854): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 6854): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/flutter ( 6854): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**To Reproduce**
Create PdfController with PdfDocument.openData:
```
PdfController(
  document: PdfDocument.openData(pdfData),
)
```

**Expected behavior**
Rendered PDF with no Issues.

**Smartphone:**
 - Device: Xiaomi Mi 9
 - OS: Android
 - Version 11

**Additional context**
On Windows works.

**Comment by wonderful89** [comment]
need to call the close method.
