### ISSUE TITLE
Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by m-amin** [ScerIO/packages.flutter#290]
Getting error when navigating back "Looking up a deactivated widget's ancestor is unsafe." using custom page builder with PhotoViewGalleryPageOptions

```
PdfView(
                backgroundDecoration: BoxDecoration(
                    color: Get.theme.primaryColor),
                controller: controller.pdfController,
                pageBuilder: (
                    Future<PdfPageImage> pageImage,
                    int index,
                    PdfDocument document,
                    ) {
                  return PhotoViewGalleryPageOptions(
                    controller: controller.photoViewController,
                    imageProvider: PdfPageImageProvider(
                      pageImage,
                      index,
                      document.id,
                      scale: 2
                    ),
                    minScale: PhotoViewComputedScale.contained * 1,
                    maxScale: PhotoViewComputedScale.contained * 3.0,
                    initialScale: PhotoViewComputedScale.contained,
                    heroAttributes: PhotoViewHeroAttributes(
                        tag: '${document.id}-$index'),
                    scaleStateController:controller.photoViewScaleStateController,
                  );
                }),
```

**Error logs:**

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4153:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4167:6)
#2      Element.getElementForInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4193:12)
#3      TickerMode.getNotifier (package:flutter/src/widgets/ticker_provider.dart:96:50)
#4      TickerProviderStateMixin._updateTickerModeNotifier (package:flutter/src/widgets/ticker_provider.dart:327:56)
#5      TickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:291:7)
#6      new AnimationController (package:flutter/src/animation/animation_controller.dart:246:21)
#7      PhotoViewCoreState._scaleAnimationController (package:photo_view/src/core/photo_view_core.dart:112:7)
#8      PhotoViewCoreState._scaleAnimationController (package:photo_view/src/core/photo_view_core.dart)
#9      PhotoViewCoreState.dispose (package:photo_view/src/core/photo_view_core.dart:274:5)
#10     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4983:11)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1926:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#16     _LayoutBuilderElement.visitChildren (package:flutter/src/widgets/layout_builder.dart:71:14)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#22     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#25     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#28     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#31     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#37     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#40     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#43     List.forEach (dart:core-patch/growable_array.dart:433:8)
#44     SliverMultiBoxAdaptorElement.visitChildren (package:flutter/src/widgets/sliver.dart:1442:52)
#45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#47     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#53     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6386:16)
#54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#56     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#59     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#62     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#65     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#71     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#76     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#77     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#78     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#79     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#81     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#82     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#84     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#85     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#87     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#88     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#89     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#90     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#91     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#92     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#93     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#94     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#95     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#96     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#97     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#98     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#99     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#100    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#101    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#102    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#103    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#104    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#105    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#106    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#107    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6386:16)
#108    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#109    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#111    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#112    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#113    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#114    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#115    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#116    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#117    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#118    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#119    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#120    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#121    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#122    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#123    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#124    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#125    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6386:16)
#126    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#127    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#128    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#129    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#130    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#131    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#132    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#133    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#134    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#135    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#136    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#137    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#138    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#139    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#140    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#141    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#142    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#143    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#144    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#145    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#146    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#147    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#148    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#149    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#150    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#151    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#152    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#153    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#154    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#155    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#156    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#157    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#158    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#159    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#160    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#161    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#162    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#163    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#164    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#165    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#166    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#167    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#168    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#169    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#170    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#171    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#172    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#173    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#174    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#175    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#176    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#177    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#178    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#179    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#180    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#181    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#182    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#183    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#184    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#185    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#186    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#187    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#188    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6386:16)
#189    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#190    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#191    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#192    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#193    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#194    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6386:16)
#195    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#196    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#197    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#198    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#199    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#200    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#201    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#202    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#203    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#204    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#205    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#206    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#207    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#208    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#209    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#210    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#211    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#212    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#213    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#214    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#215    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#216    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#217    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#218    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#219    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#220    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#221    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#222    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#223    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#224    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#225    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#226    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#227    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#228    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#229    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#230    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#231    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#232    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#233    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#234    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#235    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#236    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#237    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#238    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#239    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#240    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#241    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#242    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#243    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#244    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#245    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#246    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#247    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#248    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#249    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#250    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#251    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#252    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#253    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#254    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#255    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#256    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#257    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#258    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#259    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#260    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#261    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#262    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#263    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#264    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#265    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#266    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#267    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#268    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#269    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#270    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#271    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#272    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#273    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#274    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#275    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#276    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#277    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#278    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#279    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#280    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#281    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#282    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#283    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#284    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1935:25)
#285    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2519:15)
#286    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2932:7)
#287    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:19)
#288    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#289    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#290    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#291    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#295    _invoke (dart:ui/hooks.dart:151:10)
#296    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#297    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
```

**Comment by Miguel-Deza** [comment]
same

**Comment by rakib205** [comment]
same here

**Comment by eliseiml** [comment]
same

**Comment by rafampessoa** [comment]
same

**Comment by ncvescera** [comment]
Same problem 🦧

**Comment by ncvescera** [comment]
MAYBE I found a solution for this.

The problem is the package `photo_view` !!

Adding this inside `pubspec.yaml` resolve the problem:

```yaml
dependency_overrides:
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master
```

So your `pubspec.yaml` file should looks like this:

```yaml
name: myappname
description: My App desc.

...

dependencies:
  flutter:
    sdk: flutter

  pdfx: ^2.0.1+2

# This fix the problem
dependency_overrides:
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

...
```

This is the [link](https://stackoverflow.com/questions/70404718/error-with-photoview-looking-up-a-deactivated-widgets-ancestor-is-unsafe) where I found the fix.
