### ISSUE TITLE
[pdfx] [ANDROID] can't get second or next page

### ISSUE THREAD

**Issue by davidcz95** [ScerIO/packages.flutter#362]
**Describe the bug**
I am using pdfDocument.getPage() in for loop to get and execute actions on every page. 
And after first page it crashes with following stack trace:

```
PlatformException(PdfRendererException, io.scer.pdfx.PdfRendererException: Unknown error, Cause: null, Stacktrace: io.scer.pdfx.PdfRendererException: Unknown error
      	at io.scer.pdfx.Messages.getPage(Messages.kt:147)
      	at dev.flutter.pigeon.Pigeon$PdfxApi$-CC.lambda$setup$4(Pigeon.java:1623)
      	at dev.flutter.pigeon.-$$Lambda$Pigeon$PdfxApi$Aa0CTw_-R6CZyCn-fCfwYs-3Fw8.onMessage(Unknown Source:2)
      	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
      	at android.os.Handler.handleCallback(Handler.java:900)
      	at android.os.Handler.dispatchMessage(Handler.java:103)
      	at android.os.Looper.loop(Looper.java:219)
      	at android.app.ActivityThread.main(ActivityThread.java:8668)
      	at java.lang.reflect.Method.invoke(Native Method)
      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
      , null)
      
```

On iOS I can open multiple page without any problems...

**Expected behavior**
Open second and next pages on ANDROID

**Smartphone (please complete the following information):**
 - Device: HUAWEI P30 PRO
 - OS: Android 10 emui 12

**Comment by arcanine33** [comment]
I have same problem... Did you solve it?

**Comment by arcanine33** [comment]
I solved this problem.
It's my mistake. 

you should write this code when finished getPage method.

```
final pdx.PdfPage page = await document.getPage(i);
await page.close();
```

Even if you forget to write this code, ios is ok, but android is not.  🥹

**Comment by davidcz95** [comment]
@arcanine33 maaan! Great it works! I was closing pdfDocument instead of every page, thank you! - Closing the issue
