### ISSUE TITLE
can't open file from assets, "Not found file" problem

### ISSUE THREAD

**Issue by ivanovai0310** [ScerIO/packages.flutter#379]
Download a clean example from Github. Successfully run it, and saw examples document. Added my pdf file to assets, rebuild projects and had an error File not found. 

**To Reproduce**
1. Get a fresh example of pdfx
2.  build it
3. See everything is working fine
4. Add my pdf file.
5. Get an error.

link  to pdf

**Screenshots**
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/58144046/212567874-af03b4e4-d496-4611-a49d-548b74f9a8c5.png">

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - Pixel 6 API 29

**Additional context**
logs

Performing hot restart...
Syncing files to device Android SDK built for arm64...
Restarted application in 638ms.
E/flutter ( 3523): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(PdfRendererException, io.scer.pdfx.PdfRendererException: File not found, Cause: null, Stacktrace: io.scer.pdfx.PdfRendererException: File not found
E/flutter ( 3523): 	at io.scer.pdfx.Messages.openDocumentAsset(Messages.kt:96)
E/flutter ( 3523): 	at dev.flutter.pigeon.Pigeon$PdfxApi$-CC.lambda$setup$2(Pigeon.java:1219)
E/flutter ( 3523): 	at dev.flutter.pigeon.Pigeon$PdfxApi$$ExternalSyntheticLambda4.onMessage(Unknown Source:2)
E/flutter ( 3523): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/flutter ( 3523): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 3523): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 3523): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 3523): 	at android.os.Handler.handleCallback(Handler.java:883)
E/flutter ( 3523): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/flutter ( 3523): 	at android.os.Looper.loop(Looper.java:214)
E/flutter ( 3523): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter ( 3523): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 3523): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter ( 3523): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 3523): , null)
E/flutter ( 3523): #0      PdfxApi.openDocumentAsset (package:pdfx/src/renderer/io/pigeon.dart:598:7)
E/flutter ( 3523): <asynchronous suspension>
E/flutter ( 3523): #1      PdfxPlatformPigeon.openAsset (package:pdfx/src/renderer/io/platform_pigeon.dart:41:9)
E/flutter ( 3523): <asynchronous suspension>
E/flutter ( 3523):

**Comment by ivanovai0310** [comment]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/58144046/212568040-1052900f-2aba-4cc1-ad6b-681b9683b238.png">

**Comment by ivanovai0310** [comment]
solved. didn't add references at pubspec
